### ISSUE TITLE
Bug - Colour Picker: The Stroke Width is locking up the tool

### ISSUE THREAD

**Issue by Ion-e** [nion-software/nionswift#1183]
The issue appears inconsistently.

When adding a thick Stroke width, there seems to be a lag with the drawing.

When removing the thickness, nothing happens.

**Comment by Ion-e** [comment]
There are no outputs being printed.

However I have noticed a pattern, when you have 2 layers, If you change the Stroke width of layer 1, nothing will happen *until* you press enter on the stroke width of layer 2.

**Comment by Ion-e** [comment]
After restarting Swift, now it seems to be working fine, so haven't been able to reproduce it further.

**Comment by cmeyer** [comment]
This bug probably occurs because the inspector does not check whether the value has changed after `editing_finished` on any particular field and enters a cycle where the line width and the next field selected loop changes.

I think this issue will go away after #1093 which will use declarative and handle this situation correctly.

See also #1186.

**Comment by Ion-e** [comment]
To be tested after declarative inspector merge.

**Comment by Ion-e** [comment]
PR that fixes this has been merged. > https://github.com/nion-software/nionswift/pull/1201

**Comment by Ion-e** [comment]
Issue veryfied as fixed, tool works flawlessly now, thanks!
