### ISSUE TITLE
Adding a second layer to the line plot of a usim EELS camera display item creates a new display item

### ISSUE THREAD

**Issue by Ion-e** [nion-software/nionswift#1225]
As title and image. STR:
1. Create a display item for the usim EELS camera
2. Take a snapshot.
3. Create a composite from the usim EELS camera data item and the snapshot
4. Observe the issue.
![Image](https://github.com/user-attachments/assets/def611ac-cdba-4362-8b3a-31f2e3b7aed7)

**Comment by cmeyer** [comment]
This is intended behavior. If you start with two individual line plots, dragging one onto another creates a new display item intentionally so that the two original line plots remain intact. During acquisition, this is particularly important so that there exists a single line plot representing the EELS acquisition. In the past we had automatically "upgraded" the EELS acquisition item to be the composite line plot, but this led to confusion when trying to observe the EELS spectra alone after the composition. With the current behavior, the composite line plot is created and put in place of the single item display; but it remains relatively easy to revert back to the single display by finding the individual item and dragging it back to the display panel. With the old behavior, this was more or less impossible to accomplish.

**Comment by Ion-e** [comment]
Ah, that makes sense, excellent.

Closing as per comment, thank you!
