### ISSUE TITLE
create_tab takes a string as label parameter instead of an UILabel

### ISSUE THREAD

**Issue by kociak** [nion-software/nionswift#337]
Hi

I noticed that `Declarative.create_tab ` which should have the following signature `create_tab(self, label: UILabel, content: UIDescription)` instead works appropriately with the following signature: `create_tab(self, label: str, content: UIDescription)` .
Indeed, using a UILabel for the label parameters prints the whole UILabel dictionnary on the tab thumb, not the text of the UILabel. Using a string solves the problem.
nionswift 0.14.8

**Comment by cmeyer** [comment]
The typing for declarative uses confusing names. `UILabel` is passed as a string, whereas widgets (such as a text field or a text _label_) are typed as `UIDescription`. So calling `create_label` returns something (a dict, actually) which is typed as `UIDescription`. The reason `UILabel` is used instead of just `str` is to indicate that the label can contain a binding.

I'm closing this issue since it works as expected - but I'll try to revise the typing names in a future version to be more easily understood (i.e. rename `UIDescription` to `UIWidgetDescription`; and rename `UILabel` to `UIStringLabel` or something similar).
