### ISSUE TITLE
Baseline in line plot log plots is treated strangely

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#497]
`show(numpy.array([3,3,4,4,7,1,3,3,4,4]))`

Now drag the vertical axis so that it is constant.

Now drag the horizontal axis to be centered on the 3rd column.

Now expand the horizontal axis around the 3rd column. The baseline jumps around. This seems counterintuitive - although it is just choosing the lowest displayed value.

How does Matplotlib do it? Any thoughts?

![image](https://user-images.githubusercontent.com/34664/88977813-640f0780-d273-11ea-812e-3468a969e4e6.png)

![image](https://user-images.githubusercontent.com/34664/88977852-70936000-d273-11ea-851f-f2468933be71.png)

**Comment by Brow71189** [comment]
I see 2 issues here:
1) Some bug is preventing the data to be drawn all the way to the left edge of the plot. I'll try and track that one down.
2) There is no "natural" baseline for a log-axis like there is for a linear axis. Right now the implementation uses 1e0 (i.e. 1) as a baselinge, but I'm not sure that this is the right choice. I can also see 0 as a baseline, which would mean that the filled area reaches down infinitely when you scroll towards smaller y-values.

I didn't manage to get the same example running in matplotlib because their filled line plot does not fill from the baseline but from the minimum of the data being drawn (which looks even more awkward btw.)

Do you have any preference on the baseline in log mode?

**Comment by cmeyer** [comment]
For the natural baseline, I would look at how other programs do it: Wolfram Alpha or Mathematica, Origin, MATLAB, or Excel.
