### ISSUE TITLE
Browsing through large datasets is very slow

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#636]
To reproduce take some multi-dimensional data with a size on the order of ~10 GB. I used a 5D dataset, i.e. a sequence of 2D collection of 2D data.
In this case for example changing the displayed sequence slice takes a couple of seconds to update the display and uses about 2 GB of memory during the update. Same happens if you change either of the two collection indices.

Some more info on my test case:
Total data shape: (10, 64, 128, 276, 277)
Dtype: float32
HDF5 chunk shape on disk: (1, 1, 1, 276, 277)

Because we see the data dimensions for a 4/5D dataset, this operation is exactly aligned with the data chunks on disk. Because of this, accessing the new data slice on disk should take something on the order of a few ms. Accessing a random slice aligned with the chunks (e.g. (3, 40, 70, ...)) directly in the HDF5 dataset with the built-in console in Swift takes about 1.5 ms.

So where is this factor of 1000 in speed coming from?

**Comment by cmeyer** [comment]
The problem was the general algorithm for reducing a sequence of collections of datums was to first take the sequence slice and then the collection slice to get the datum slice. The fix was to combine those two operations into a single slice operation to grab the sequence and collection slice at once. The fix does not optimize the case of summing the collection slice (i.e. a pick operation); but it handles the reported 5D case very well.
