### ISSUE TITLE
PytzUsageWarning in Utility

### ISSUE THREAD

**Issue by kociak** [nion-software/nionswift#780]
I get an error message reported at the end of this comment when I am using a `computation` (either mine, or you can try with e.g calibrate spectrum). I don't see any traceback so I can't be more specific, but my understanding it that the message is triggerred everytime a dataitem "date" (the date with time seen under a dataitem widget in the data panel) is updated.
Message
```
/opt/miniconda3/envs/developper/lib/python3.9/site-packages/nion/swift/model/Utility.py:77: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzlocal.get_localzone().zone if local_timezone_override is None else local_timezone_override[0]
```

**Comment by cmeyer** [comment]
This was probably fixed in these two commits:

3a5e7c397ab836dcac9a839df4e3b8dbc40d93fe 2021-08-17 Make tzlocal code compatible with v2 or v3.
0afe2313eaecfdd766fd2e60a648431b6986c087 2021-10-25 Another attempt to standardize tzlocal usage.

If you see it again, add a comment here or re-open the issue.
