### ISSUE TITLE
Hitting return on a line plot data item scales x-axis incorrectly when no intervals selected

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#939]
If you double click on the x-axis, the scaling is correct:

<img width="331" alt="double click" src="https://user-images.githubusercontent.com/16721195/217286841-b9717f48-f23f-4ea6-bece-21021bbcd938.PNG">

Hitting return adds some extra margin:

<img width="323" alt="return" src="https://user-images.githubusercontent.com/16721195/217287028-5355a14a-6fcd-4e72-8ab9-e9604c530437.PNG">

This was reported by a customer but if this is intended behavior feel free to just close this.

**Comment by TomaSusi** [comment]
Customer here ;) This certainly does not feel like correct behavior for a user.

**Comment by cmeyer** [comment]
If intervals are selected, the return key will zoom to those selected intervals and is supposed to add padding on either side of the interval so that the intervals don't end up at the edges of the display. When no intervals are selected it probably makes more sense to have the behavior the same as double clicking on the axis.

**Comment by TomaSusi** [comment]
Right, makes sense with the intervals but that's not the case here.

**Comment by cmeyer** [comment]
Also this code (see 0556bbe9cf873c2b7180b1da8df9025ec212ddad) deals with multiple layers, so the fix is relatively easy, but not trivial.
