### ISSUE TITLE
Can't catch document_controller.focused_display_item_changed_event Event 

### ISSUE THREAD

**Issue by kociak** [nion-software/nionswift#957]
Trying to get notified of a change in focused display_item fails.
Below is a minimal handler to reproduce the fail.

```
class MinimalHandler:
    def __init__(self, document_controller: DocumentController.DocumentController):
        self.document_controller = document_controller
        self.focus_changed_event_listener = self.document_controller.focused_display_item_changed_event.listen(
            self.focus_updated)
    
    def focus_updated(self,display_item):
        data_item = display_item.data_item if display_item else None
        print(f"focus updated {data_item}")
```

using swift 0.16.8 on Mac OS

**Comment by kociak** [comment]
To make it clear: `focus_updated` is never called when I switch from one data item to the other on the interface. But the inspector and histogram works well so I guess the event is fired.
Also, I tried to add the following line in the handler
`self.document_controller.focused_display_item_changed_event.fire(None)`
and it works, ie, `focus_updated` is called.

**Comment by cmeyer** [comment]
In regular use of the software, this is only fired from one location: `__update_selected_display_items`, so you can put a `print` statement just before it fires and see that it is firing correctly.

If it isn't, it may be due to another local modification on your system preventing it; or the `focus_changed_event_listener` variable has somehow been garbage collected.

Standard disclaimer: this event is part of internal code and there is no guarantee that it will continue to function like this. I've already been migrating towards using `ValueStreams` for tracking the display item. This means that in the [current trunk code](https://github.com/nion-software/nionswift/commit/920a56343b734767703f0a8a9ba434bcffe10b04) as of today that the `TargetDisplayItemStream` in `HistogramPanel.py` will eventually migrate to the `DocumentController` and will become the standard way of observing the current display item.

**Comment by cmeyer** [comment]
Your minimal example looks correct. Are any exceptions being thrown? Also, is it possible that `MinimalHandler` itself is being garbage collected?

Also, there is no better way to do it currently - I just want to add the disclaimer that it may change in the future and you would need to update your code. This usually wouldn't be a big change.

**Comment by kociak** [comment]
You spotted it! Incredible GC mechanisms.
Indeed, the MinimalHandler was garbage collected. To fix this, I changed the MinimalView, which was only consisting in a `label` without binding, to a `pushbutton` referring to a function attribute of the MinimalHandler. I think this indicated to the GC not to delete the MinimalHandler. Probably indicating bindings would do the job, too. Thanks for the hint, I would never have guessed that!
